### ISSUE TITLE
Generate email with questions for pollick

### ISSUE THREAD

**Issue by ErrolKeith** [ErrolKeith/RFP#1]
Generate one email with all of the teams questions for the proposal to clarify anything we need. All emails and responses need to be turned in with the project. This should be easier if we make a list of things to ask and send in one single project.

**Comment by savursool247** [comment]
we need to discuss what kinds of things we need clarification on in order to complete the program

**Comment by savursool247** [comment]
Question about the details of Example Corp have been sent

**Comment by savursool247** [comment]
Questions about the operations hours for Example Corp have been sent. This is needed to write about the integration process for this software

**Comment by savursool247** [comment]
All questions have been asked
