### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ErrolKeith** [ErrolKeith/RFP#2]
We either need to generate our own methods of voicemail hosting to answer the questions in the assignment, or use a service that provides hosting. If we choose the second, we need to answer the questions based on the company website.

**Comment by savursool247** [comment]
i have no problem helping to find a company that can host mailboxes, but it may not meet all the reqs. I will try to find a company and hold on to the link so we can discuss more.

**Comment by savursool247** [comment]
After searching for hosting companies like MS Exchange using Outlook, and NEC's PBX software, we decided it would be cheaper to do all installation and hardware integration ourselves, including the creation of the software.

**Comment by savursool247** [comment]
the budget has been updated to reflect our in-house installation and pbx management, and details including security, power backup, and more
