### ISSUE TITLE
list out requirements

### ISSUE THREAD

**Issue by ErrolKeith** [ErrolKeith/RFP#3]

**Comment by savursool247** [comment]
Each user will have a valid mailbox and a password

User must be able to:
**Play back messages
Delete messages
Change the greeting
Change the password**

Administrators must be able to:
**Activate mailboxes
Deactivate mailboxes
Play messages
Copy messages**

Adjust this list accordingly

**Comment by savursool247** [comment]
Requirements have been listed and reviewed by me
