### ISSUE TITLE
create use cases for each requirement

### ISSUE THREAD

**Issue by ErrolKeith** [ErrolKeith/RFP#4]

**Comment by savursool247** [comment]
Each user will have a valid mailbox and a password
User must be able to:
**Play back messages
Delete messages
Change the greeting
Change the password**

Administrators must be able to:
**Activate mailboxes
Deactivate mailboxes
Play messages
Copy messages**

**Comment by savursool247** [comment]
use cases by me are done, just waiting for review from the team
[project7_UserStories_Table.xlsx](https://github.com/ErrolKeith/RFP/files/4533416/project7_UserStories_Table.xlsx)

**Comment by savursool247** [comment]
use cases have been reviewed and completed by the team
